CREATE TABLE `Person` (
 `codePerson` bigint(20) NOT NULL,
  `typePerson` varchar(100) NOT NULL,
  `identify` varchar(100) DEFAULT NULL,
  `typeIdentify` varchar(100) DEFAULT NULL,
  `firstName` varchar(100) NOT NULL,
  `middleName` varchar(100) NOT NULL,
  `lastName` varchar(100) NOT NULL,
  `lastNameMatern` varchar(100) NOT NULL,
  `academicDegree` varchar(100) NOT NULL,
  `name` varchar(100) DEFAULT NULL,
  `country` varchar(100) DEFAULT NULL,
  `birthday` date DEFAULT NULL,
  `status` varchar(100) DEFAULT NULL,
  `sex` varchar(100) NOT NULL,
  `dateCreate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dateLastModify` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `userCreate` bigint(20) NOT NULL,
  `userLastModify` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8
